apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec: 
  containers:
    - name: nodeapp
      image: junaidshaikhcr7/testrepo:node-docker
      ports:
        - containerPort: 8080
