apiVersion: v1
kind: Pod
metadata:
  name: nodehello
  labels:
    app: nodehello
spec: 
  containers:
    - name: nodeapp
      image: junaidshaikhcr7/testrepo:node-docker
      ports:
        - containerPort: 8080
